/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package busreservationsystem;

import javax.swing.JOptionPane;

/**
 *
 * @author SherifMounir
 */
public class AddBus extends javax.swing.JFrame {

    /**
     * Creates new form AddBus
     */
    public AddBus() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nameLabel = new javax.swing.JLabel();
        busnumber = new javax.swing.JTextField();
        numberLabel = new javax.swing.JLabel();
        fare = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        distance = new javax.swing.JTextField();
        registerButton = new javax.swing.JButton();
        nameLabel1 = new javax.swing.JLabel();
        busroute = new javax.swing.JTextField();
        nameLabel3 = new javax.swing.JLabel();
        busid = new javax.swing.JTextField();
        numberLabel1 = new javax.swing.JLabel();
        status = new javax.swing.JTextField();
        numberofseats = new javax.swing.JTextField();
        numberLabel2 = new javax.swing.JLabel();
        bustype = new javax.swing.JTextField();
        numberLabel3 = new javax.swing.JLabel();
        busdescription = new javax.swing.JTextField();
        numberLabel4 = new javax.swing.JLabel();
        driver = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        nameLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nameLabel.setText("Bus Number");

        busnumber.setToolTipText("");
        busnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busnumberActionPerformed(evt);
            }
        });

        numberLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numberLabel.setText("Fare");

        fare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fareActionPerformed(evt);
            }
        });

        passwordLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        passwordLabel.setText("Number Of Seats");

        addressLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addressLabel.setText("Distance");

        registerButton.setText("Save");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        nameLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nameLabel1.setText("Route");

        busroute.setToolTipText("");
        busroute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busrouteActionPerformed(evt);
            }
        });

        nameLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        nameLabel3.setText("Bus ID");

        busid.setToolTipText("");
        busid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busidActionPerformed(evt);
            }
        });

        numberLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numberLabel1.setText("Status");

        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });

        numberofseats.setToolTipText("");
        numberofseats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberofseatsActionPerformed(evt);
            }
        });

        numberLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numberLabel2.setText("Type");

        bustype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bustypeActionPerformed(evt);
            }
        });

        numberLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numberLabel3.setText("Description");

        busdescription.setToolTipText("");
        busdescription.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                busdescriptionActionPerformed(evt);
            }
        });

        numberLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        numberLabel4.setText("Driver");

        driver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                driverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(status, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addComponent(numberLabel1)
                    .addComponent(busroute)
                    .addComponent(numberLabel)
                    .addComponent(nameLabel1)
                    .addComponent(busid, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressLabel)
                    .addComponent(passwordLabel)
                    .addComponent(fare)
                    .addComponent(distance)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(nameLabel3)
                        .addGap(15, 15, 15))
                    .addComponent(numberofseats))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(busnumber, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel)
                    .addComponent(numberLabel2)
                    .addComponent(bustype, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                    .addComponent(numberLabel3)
                    .addComponent(busdescription)
                    .addComponent(numberLabel4)
                    .addComponent(driver))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel3)
                    .addComponent(nameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(busnumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(busid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passwordLabel)
                    .addComponent(numberLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberofseats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bustype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameLabel1)
                    .addComponent(numberLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(busroute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(busdescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel)
                    .addComponent(numberLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(distance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(driver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numberLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fare, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(numberLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(registerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 459, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void busnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busnumberActionPerformed

    }//GEN-LAST:event_busnumberActionPerformed

    private void fareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fareActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fareActionPerformed

    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed

        if(this.busid.getText().isEmpty()|| this.busnumber.getText().isEmpty() || this.busdescription.getText().isEmpty() ||
            this.busroute.getText().isEmpty() || this.bustype.getText().isEmpty() || this.fare.getText().isEmpty() || this.distance.getText().isEmpty() || this.status.getText().isEmpty() || this.numberofseats.getText().isEmpty() || this.driver.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Empty Field", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

        else
        {
             
            //Bus bus = new Bus(Integer.parseInt(this.busid.getText()), Integer.parseInt(this.busnumber.getText()), this.busroute.getText(), this.distance.getText(), this.fare.getText(), this.status.getText(),Integer.parseInt(this.numberofseats.getText()) , this.bustype.getText(), this.busdescription.getText(), this.driver.getText());
           // bus.saveBusInfoInFile();
           // HomePage.Buses.add(bus);
            Admin a = new Admin();
            a.addBus(Integer.parseInt(this.busid.getText()), Integer.parseInt(this.busnumber.getText()), this.busroute.getText(), this.distance.getText(), this.fare.getText(), this.status.getText(),Integer.parseInt(this.numberofseats.getText()) , this.bustype.getText(), this.busdescription.getText(), this.driver.getText());
            JOptionPane.showMessageDialog(null, "Saved Successfully");
            AdminDashboard Page = new AdminDashboard();
            Page.setVisible(true);
            Page.setLocationRelativeTo(null);
            dispose();

        }

    }//GEN-LAST:event_registerButtonActionPerformed

    private void busrouteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busrouteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_busrouteActionPerformed

    private void busidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_busidActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed

    private void numberofseatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberofseatsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberofseatsActionPerformed

    private void bustypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bustypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bustypeActionPerformed

    private void busdescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_busdescriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_busdescriptionActionPerformed

    private void driverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_driverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_driverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JTextField busdescription;
    private javax.swing.JTextField busid;
    private javax.swing.JTextField busnumber;
    private javax.swing.JTextField busroute;
    private javax.swing.JTextField bustype;
    private javax.swing.JTextField distance;
    private javax.swing.JTextField driver;
    private javax.swing.JTextField fare;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nameLabel1;
    private javax.swing.JLabel nameLabel3;
    private javax.swing.JLabel numberLabel;
    private javax.swing.JLabel numberLabel1;
    private javax.swing.JLabel numberLabel2;
    private javax.swing.JLabel numberLabel3;
    private javax.swing.JLabel numberLabel4;
    private javax.swing.JTextField numberofseats;
    private javax.swing.JLabel passwordLabel;
    private javax.swing.JButton registerButton;
    private javax.swing.JTextField status;
    // End of variables declaration//GEN-END:variables
}
